from dotenv import load_dotenv
import os
load_dotenv()
DATABASE_HOST = os.getenv("DATABASE_HOST")
DATEBASE_NAME=  os.getenv("DATABASE_NAME")
DATABASE_USER =  os.getenv("DATABASE_USER")
DATABASE_PASSWORD =  os.getenv("DATABASE_PASSWORDS")

DATABASE_CONNECTION_URI='mysql://{DATEBASE_NAME}:{DATABASE_PASSWORD}@{DATABASE_HOST}/{DATEBASE_NAME}'